# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5fe92b4e530ea477799fb6ab6936bda4f522f1a968818c1731b1861f02152d6eaf10eae6bfa96a53575fec354665625f2a1dbfdcae52e3123addacd10a54f43

test:
  secret_key_base: f99f677ae085affc30fe7231ebed0940161e272b92cf425e223039eb80f64a1920b4314af5f2fb8c57357094a21bca78313481818873706f785bd42ef4f8822e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
